import type {
  Team,
  RiskAlert,
  Recommendation,
  HealthMetrics,
  AbsenteeismMetrics,
  ProductivityMetrics,
  AIAdoptionMetrics,
  FinancialMetrics,
  Notification,
  User,
} from "./types";

export const currentUser: User = {
  name: "Sarah Johnson",
  email: "sarah.johnson@acme.com",
  role: "executive",
  company: "Acme Corporation",
};

export const teams: Team[] = [
  {
    id: "1",
    name: "Sales Team",
    department: "Sales",
    headCount: 45,
    healthIndex: 62,
    riskScore: 78,
    riskLevel: "high",
    riskType: "Stress & Burnout",
    trend: -8,
    productivityImpact: 15,
    financialImpact: 125000,
    absenteeismRate: 12,
    stressLevel: 82,
    activityLevel: 58,
    aiAdoption: 34,
  },
  {
    id: "2",
    name: "Engineering",
    department: "Technology",
    headCount: 78,
    healthIndex: 71,
    riskScore: 45,
    riskLevel: "medium",
    riskType: "Low Activity",
    trend: -3,
    productivityImpact: 8,
    financialImpact: 89000,
    absenteeismRate: 6,
    stressLevel: 55,
    activityLevel: 42,
    aiAdoption: 67,
  },
  {
    id: "3",
    name: "Customer Support",
    department: "Operations",
    headCount: 32,
    healthIndex: 58,
    riskScore: 82,
    riskLevel: "critical",
    riskType: "High Absenteeism",
    trend: -12,
    productivityImpact: 22,
    financialImpact: 156000,
    absenteeismRate: 18,
    stressLevel: 75,
    activityLevel: 51,
    aiAdoption: 28,
  },
  {
    id: "4",
    name: "Marketing",
    department: "Marketing",
    headCount: 24,
    healthIndex: 79,
    riskScore: 28,
    riskLevel: "low",
    riskType: "Stable",
    trend: 5,
    productivityImpact: 3,
    financialImpact: 18000,
    absenteeismRate: 4,
    stressLevel: 38,
    activityLevel: 72,
    aiAdoption: 56,
  },
  {
    id: "5",
    name: "Finance",
    department: "Finance",
    headCount: 18,
    healthIndex: 74,
    riskScore: 35,
    riskLevel: "low",
    riskType: "Stable",
    trend: 2,
    productivityImpact: 5,
    financialImpact: 32000,
    absenteeismRate: 5,
    stressLevel: 42,
    activityLevel: 68,
    aiAdoption: 45,
  },
  {
    id: "6",
    name: "HR",
    department: "Human Resources",
    headCount: 12,
    healthIndex: 85,
    riskScore: 18,
    riskLevel: "low",
    riskType: "Stable",
    trend: 8,
    productivityImpact: 2,
    financialImpact: 8000,
    absenteeismRate: 3,
    stressLevel: 28,
    activityLevel: 78,
    aiAdoption: 72,
  },
  {
    id: "7",
    name: "Product",
    department: "Technology",
    headCount: 28,
    healthIndex: 68,
    riskScore: 52,
    riskLevel: "medium",
    riskType: "Workload Imbalance",
    trend: -5,
    productivityImpact: 10,
    financialImpact: 67000,
    absenteeismRate: 7,
    stressLevel: 62,
    activityLevel: 55,
    aiAdoption: 61,
  },
];

export const healthMetrics: HealthMetrics = {
  overall: 72,
  chronic: 15,
  stress: 42,
  activity: 64,
  trend: -3,
};

export const absenteeismMetrics: AbsenteeismMetrics = {
  totalDaysLost: 1247,
  shortTerm: 823,
  longTerm: 424,
  trend: 8,
  topReasons: [
    { reason: "Stress-related", count: 312 },
    { reason: "Physical illness", count: 284 },
    { reason: "Mental health", count: 198 },
    { reason: "Back/Musculoskeletal", count: 167 },
    { reason: "Other", count: 286 },
  ],
};

export const productivityMetrics: ProductivityMetrics = {
  productivityLoss: 12,
  highImpactTeams: [
    { name: "Customer Support", loss: 22 },
    { name: "Sales Team", loss: 15 },
    { name: "Product", loss: 10 },
    { name: "Engineering", loss: 8 },
  ],
};

export const aiAdoptionMetrics: AIAdoptionMetrics = {
  activeUsers: 156,
  totalUsers: 237,
  adoptionRate: 66,
  dauWau: 0.72,
  trend: 12,
  topTopics: [
    { topic: "Stress Management", count: 892 },
    { topic: "Sleep Improvement", count: 654 },
    { topic: "Nutrition", count: 421 },
    { topic: "Exercise", count: 389 },
    { topic: "Work-Life Balance", count: 356 },
  ],
};

export const financialMetrics: FinancialMetrics = {
  totalCostImpact: 2340000,
  productivityLossCost: 1560000,
  absenteeismCost: 780000,
  roi: 342,
  preventedLosses: 890000,
  productivityImprovement: 18,
  claimsReduction: 245000,
  highCostAvoidance: 156000,
};

export const riskAlerts: RiskAlert[] = [
  {
    id: "1",
    title: "Stress Rising in Sales",
    description: "Stress indicators have increased by 15% over the past 2 weeks",
    severity: "high",
    teamId: "1",
    teamName: "Sales Team",
    productivityImpact: 15,
    costImpact: 125000,
    trend: "rising",
  },
  {
    id: "2",
    title: "Low Activity in Engineering",
    description: "Physical activity levels dropped below healthy threshold",
    severity: "medium",
    teamId: "2",
    teamName: "Engineering",
    productivityImpact: 8,
    costImpact: 89000,
    trend: "stable",
  },
  {
    id: "3",
    title: "Critical Absenteeism in Support",
    description: "Absenteeism rate exceeded 15% threshold",
    severity: "critical",
    teamId: "3",
    teamName: "Customer Support",
    productivityImpact: 22,
    costImpact: 156000,
    trend: "rising",
  },
  {
    id: "4",
    title: "Burnout Risk in Product",
    description: "Extended overtime patterns detected across team",
    severity: "medium",
    teamId: "7",
    teamName: "Product",
    productivityImpact: 10,
    costImpact: 67000,
    trend: "rising",
  },
];

export const recommendations: Recommendation[] = [
  {
    id: "1",
    title: "Implement Stress Management Program",
    problem: "Sales team showing elevated stress levels affecting performance",
    impact: { productivity: 15, cost: 125000 },
    action: "Launch 4-week mindfulness and workload balancing initiative",
    status: "pending",
    teamId: "1",
    teamName: "Sales Team",
    priority: "high",
  },
  {
    id: "2",
    title: "Activity Challenge for Engineering",
    problem: "Low physical activity contributing to decreased energy and focus",
    impact: { productivity: 8, cost: 89000 },
    action: "Introduce step challenge with incentives and standing desk options",
    status: "pending",
    teamId: "2",
    teamName: "Engineering",
    priority: "medium",
  },
  {
    id: "3",
    title: "Support Team Restructuring",
    problem: "High absenteeism indicating understaffing and burnout",
    impact: { productivity: 22, cost: 156000 },
    action: "Add 3 FTEs and implement shift rotation improvements",
    status: "pending",
    teamId: "3",
    teamName: "Customer Support",
    priority: "high",
  },
  {
    id: "4",
    title: "AI Assistant Adoption Campaign",
    problem: "Low adoption in high-risk teams limits intervention effectiveness",
    impact: { productivity: 5, cost: 45000 },
    action: "Targeted onboarding sessions for Sales and Support teams",
    status: "pending",
    priority: "medium",
  },
  {
    id: "5",
    title: "Flexible Work Hours for Product",
    problem: "Extended overtime patterns creating burnout risk",
    impact: { productivity: 10, cost: 67000 },
    action: "Implement core hours policy and async work guidelines",
    status: "applied",
    teamId: "7",
    teamName: "Product",
    priority: "high",
  },
];

export const notifications: Notification[] = [
  {
    id: "1",
    title: "Critical Risk Alert",
    message: "Customer Support absenteeism exceeded threshold",
    type: "risk",
    read: false,
    timestamp: new Date(Date.now() - 1000 * 60 * 30),
  },
  {
    id: "2",
    title: "Stress Alert",
    message: "Sales team stress indicators rising",
    type: "risk",
    read: false,
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 2),
  },
  {
    id: "3",
    title: "Report Generated",
    message: "Monthly workforce health report is ready",
    type: "info",
    read: true,
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24),
  },
  {
    id: "4",
    title: "System Update",
    message: "New AI insights features available",
    type: "system",
    read: true,
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 48),
  },
];

// Trend data for charts
export const healthTrendData = [
  { month: "Jan", health: 68, stress: 45, activity: 58 },
  { month: "Feb", health: 70, stress: 42, activity: 62 },
  { month: "Mar", health: 72, stress: 40, activity: 65 },
  { month: "Apr", health: 71, stress: 44, activity: 63 },
  { month: "May", health: 74, stress: 38, activity: 68 },
  { month: "Jun", health: 72, stress: 42, activity: 64 },
];

export const absenteeismTrendData = [
  { month: "Jan", shortTerm: 145, longTerm: 72 },
  { month: "Feb", shortTerm: 132, longTerm: 68 },
  { month: "Mar", shortTerm: 128, longTerm: 65 },
  { month: "Apr", shortTerm: 142, longTerm: 70 },
  { month: "May", shortTerm: 138, longTerm: 74 },
  { month: "Jun", shortTerm: 138, longTerm: 75 },
];

export const productivityByDeptData = [
  { department: "Sales", loss: 15 },
  { department: "Engineering", loss: 8 },
  { department: "Support", loss: 22 },
  { department: "Marketing", loss: 3 },
  { department: "Finance", loss: 5 },
  { department: "Product", loss: 10 },
];

export const financialTrendData = [
  { month: "Jan", cost: 380000, savings: 120000 },
  { month: "Feb", cost: 365000, savings: 135000 },
  { month: "Mar", cost: 350000, savings: 150000 },
  { month: "Apr", cost: 395000, savings: 125000 },
  { month: "May", cost: 410000, savings: 145000 },
  { month: "Jun", cost: 390000, savings: 165000 },
];

export const correlationData = [
  { healthIndex: 85, productivity: 95 },
  { healthIndex: 79, productivity: 88 },
  { healthIndex: 74, productivity: 82 },
  { healthIndex: 72, productivity: 80 },
  { healthIndex: 71, productivity: 78 },
  { healthIndex: 68, productivity: 72 },
  { healthIndex: 62, productivity: 65 },
  { healthIndex: 58, productivity: 58 },
];

export const aiUsageTrendData = [
  { week: "W1", users: 98, engagement: 45 },
  { week: "W2", users: 112, engagement: 52 },
  { week: "W3", users: 128, engagement: 58 },
  { week: "W4", users: 142, engagement: 62 },
  { week: "W5", users: 148, engagement: 68 },
  { week: "W6", users: 156, engagement: 72 },
];
